### ISSUE TITLE
Python Run object complains of $_ values

### ISSUE THREAD

**Issue by arezaii** [parflow/parflow#290]
Since the update from 0.0.6 to 1.0.0, my script is no longer working, with the error that the Solver and Preconditioner keys are not getting set.

**Steps to Reproduce:**
```
from parflow.tools import Run
sim = Run('my_simulation')
sim = sim.from_definition(file_path='subset_watershed.conus1.parking_lot.yaml')
sim.validate(verbose=True)
```

**Actual Results:**
```
Field $_ is not part of the expected schema <class 'parflow.tools.database.generated.Solver'>
Field $_ is not part of the expected schema <class 'parflow.tools.database.generated.Preconditioner'>
...all keys before validate with green checks
   Solver: 
    TerrainFollowingGrid: 
    Linear: 
      Preconditioner: 
        PCMatrixType: PFSymmetric ✔
        $_: PFMGOctree
      KrylovDimension: 20 ✔
      MaxRestart: 2 ✔
    Nonlinear:
      VariableDz: True ✔
      ResidualTol: 1e-06 ✔
      StepTol: 1e-30 ✔
      MaxIter: 50 ✔
      EtaChoice: EtaConstant ✔
      EtaValue: 0.01 ✔
      UseJacobian: 
      DerivativeEpsilon: 1e-16 ✔
      Globalization: 
    AbsTol: 
    Drop: 1e-30 ✔
    MaxIter: 10000000 ✔
    PrintSubsurf: False ✔
    $_: Richards
...all keys after validate with green checks (one delta)

# ==============================================================================
# ParFlow directory
#  - /home/arezaii/pfdir/install
# ParFlow version
#  - 3.7.0
# Working directory
#  - /home/arezaii/pf_subsetter_testing/9673496c85b241c303d539a301641894f77ac86b
# ParFlow database
#  - subset_watershed.conus1.parking_lot.pfidb
# ==============================================================================

# ==============================================================================
# ParFlow run failed. ❌ ❌ ❌  Contents of error output file:
--------------------------------------------------------------------------------
Node 0: Using process grid (2,1,1)

--------------------------------------------------------------------------------
# ==============================================================================

An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
```

**Expected Results:**
Validation completes, and completing the process with: 
```
sim.dist(sim.TopoSlopesX.FileName)
sim.dist(sim.TopoSlopesY.FileName)
sim.run()
```
completes without error

**Other notes:**
I looked at the generated `.pfidb` file and it looks like the key values are getting set to `$_` for these two keys.

`YAML` input file used and the `pfidb` file that `Run.run()` generated: 
[subset_watershed.conus1.parking_lot.zip](https://github.com/parflow/parflow/files/5557190/subset_watershed.conus1.parking_lot.zip)

edit* Adding the full environment info:
[conda_list.txt](https://github.com/parflow/parflow/files/5557218/conda_list.txt)

relevant portion at line 104: `pftools                   1.0.0                    pypi_0    pypi`
